from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Business Partnership Analysis Queries",
    description="Queries for analyzing business partnership communication patterns.",
    questions=[
        "What strategic decisions and business plans do the partners discuss?",
        "How do they divide responsibilities and assign tasks to each other?",
        "What financial discussions and budget planning conversations occur?",
        "How do they handle disagreements about business direction?",
        "What client relationships and customer feedback do they share?",
        "How do they communicate about hiring and team management decisions?",
        "What market opportunities and competitive analysis do they discuss?",
        "How do they coordinate their schedules and meeting arrangements?",
        "What concerns about business risks and challenges do they express?",
        "How do they celebrate business milestones and achievements together?",
        "What innovative ideas and creative solutions do they brainstorm?",
        "How do they communicate about work-life balance and personal boundaries?",
        "What vendor relationships and supplier negotiations do they coordinate?",
        "How do they handle crisis management and urgent business issues?",
        "What long-term vision and growth strategies do they plan together?",
        "How do they provide feedback and constructive criticism to each other?",
        "What legal matters and compliance issues do they address?",
        "How do they coordinate marketing and promotional activities?",
        "What technology implementations and system upgrades do they discuss?",
        "How do they manage conflicts of interest or competing priorities?",
        "What industry trends and market research do they share?",
        "How do they handle performance reviews and business metrics?",
        "What networking opportunities and professional events do they coordinate?",
        "How do they communicate about equity, ownership, and profit sharing?",
        "What quality control and operational improvements do they discuss?",
        "How do they delegate authority and make executive decisions together?",
        "What succession planning and exit strategies do they consider?",
        "How do they handle confidential information and trade secrets?",
        "What partnership agreements and contract modifications do they negotiate?",
        "How do they coordinate investor relations and funding discussions?",
        "What employee relations and HR issues do they address together?",
        "How do they balance individual strengths with collective decision-making?",
        "What competitive advantages and unique value propositions do they develop?",
        "How do they communicate during high-stress periods and deadlines?",
        "What professional development and skill-building do they discuss?",
        "How do they handle disagreements about company culture and values?",
        "What international expansion and market entry strategies do they explore?",
        "How do they coordinate public relations and brand management efforts?",
        "What sustainability initiatives and social responsibility do they plan?",
        "How do they evaluate and adjust their partnership dynamics over time?"
    ]
)
