from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Couple Queries",
    description="Queries for analyzing relationships between two people.",
    questions=[
        "What did the husband and wife discuss regarding dinner plans?",
        "What weekend plans did they mention?",
        "Did they discuss any vacation plans in their messages?",
        "What did they discuss regarding the husband’s birthday?",
        "Did they discuss future plans, such as travel or major purchases?",
        "What topics came up most frequently in their messages?",
        "Did they argue or disagree about anything in their communication?",
        "What did they say about household repairs or renovations?",
        "What was mentioned about the wife’s job or work?",
        "What common hobbies or interests did they discuss?",
        "What was the overall tone of their communication?",
        "Were there messages where the wife seemed upset or distressed?",
        "In which instances did the husband express enthusiasm or joy?",
        "Did they express support for each other in their messages?",
        "How did they show love or affection in their communication?",
        "Which messages indicate a deep emotional connection?",
        "What did the wife say about the new restaurant?",
        "What did they say about buying a car?",
        "Were there messages where either of them said, 'I love you'?",
        "Did they mention any funny or amusing moments from their lives?",
        "Who typically suggested ideas for dinner in their conversations?",
        "Did they discuss who would pick up the children from school?",
        "What did they say about financial expenses or budgeting?",
        "Who usually organized family events or activities in their messages?",
        "How did they support each other in achieving personal goals?",
        "How did their communication tone change over time?",
        "What significant events did they discuss in their messages?",
        "Were there periods when they communicated less frequently?",
        "What promises or commitments did they make to each other?",
        "Were there moments when they felt misunderstood by each other?",
        "How did they handle conflicts or disagreements in their messages?",
        "What did the wife say about her favorite TV show?",
        "Did the husband mention any sports events?",
        "What did they discuss about gifts for each other?",
        "Which vacation destinations or leisure spots did they mention?",
        "How did they share everyday joys or successes with each other?",
        "How often did they discuss their feelings for each other?",
        "Which topics led to the greatest mutual understanding or agreement?",
        "Did they discuss any fears or anxieties?",
        "How did they support each other during difficult moments?",
        "Did they mention their dreams or aspirations?",
        "How did they express gratitude or appreciation to each other?",
        "What relationship challenges can be inferred from their communication?",
        "What questions should be asked of a family therapist to address the most critical issues in their relationship?",
        "How did they plan their future together?",
        "Did they discuss parenting or child-rearing matters?",
        "What compliments did they give each other?",
        "What shared activities or favorite pastimes did they mention?",
        "How did they plan surprises or gifts for each other?"
    ]
)
