from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Customer Support Analysis Queries",
    description="Queries for analyzing customer support communication patterns.",
    questions=[
        "What are the most common issues and problems customers report?",
        "How do support agents demonstrate empathy and understanding?",
        "What solution approaches and troubleshooting steps are most effective?",
        "How quickly do agents respond to different types of customer inquiries?",
        "What follow-up actions and additional support do agents provide?",
        "How do agents handle frustrated or angry customer interactions?",
        "What technical explanations and guidance do agents provide clearly?",
        "How do they escalate complex issues to specialized teams or supervisors?",
        "What proactive suggestions and preventive advice do agents offer?",
        "How do they verify customer identity and account information securely?",
        "What refund, exchange, and compensation discussions occur most frequently?",
        "How do agents personalize their communication to individual customers?",
        "What product knowledge and expertise do agents demonstrate consistently?",
        "How do they handle multiple customer conversations simultaneously?",
        "What customer satisfaction feedback and ratings do interactions receive?",
        "How do agents collaborate with internal teams to resolve customer issues?",
        "What documentation and case management practices do they follow?",
        "How do they communicate complex policies and procedures clearly?",
        "What upselling and cross-selling opportunities do they identify appropriately?",
        "How do they handle customers who request to speak with managers?",
        "What seasonal or trending issues require specialized communication approaches?",
        "How do agents maintain professional tone while being friendly and helpful?",
        "What language barriers and communication challenges do they navigate?",
        "How do they handle customers with accessibility needs or special requirements?",
        "What feedback about product improvements do they collect from customers?",
        "How do they manage customer expectations about resolution timelines?",
        "What training gaps or knowledge deficiencies become apparent in conversations?",
        "How do experienced agents mentor and guide newer team members?",
        "What automation and chatbot interactions transition smoothly to human agents?",
        "How do they handle privacy concerns and data security questions?",
        "What cultural sensitivity and global customer considerations do they address?",
        "How do they communicate bad news or limitations effectively to customers?",
        "What success stories and positive outcomes do they achieve regularly?",
        "How do they handle customers who have had previous negative experiences?",
        "What competitive comparisons and alternative solutions do they discuss?",
        "How do they maintain consistency in messaging across different agents?",
        "What emotional labor and stress management challenges do agents face?",
        "How do they adapt their communication style to different customer personalities?",
        "What process improvements and efficiency gains emerge from customer feedback?",
        "How do they balance individual customer needs with company policies and limitations?"
    ]
)
