from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Dating Analysis Queries",
    description="Queries for analyzing relationships between family members.",
    questions=[
        "What future plans and relationship goals do they discuss together?",
        "How do they express their feelings and emotional connection?",
        "What date ideas and romantic activities do they plan?",
        "How do they handle disagreements and resolve conflicts?",
        "What personal values and life philosophies do they share?",
        "How do they communicate about physical intimacy and boundaries?",
        "What family backgrounds and childhood experiences do they share?",
        "How do they support each other's career goals and ambitions?",
        "What shared interests and hobbies do they discover together?",
        "How do they navigate introducing each other to friends and family?",
        "What financial expectations and money management do they discuss?",
        "How do they handle jealousy and trust issues in the relationship?",
        "What communication preferences and styles do they establish?",
        "How do they balance independence with togetherness?",
        "What past relationship experiences do they share with each other?",
        "How do they handle long-distance periods or time apart?",
        "What pet peeves and annoying habits do they address?",
        "How do they show appreciation and gratitude toward each other?",
        "What religious or spiritual beliefs do they explore together?",
        "How do they handle different social media and privacy preferences?",
        "What deal-breakers and non-negotiable values do they identify?",
        "How do they navigate different love languages and affection styles?",
        "What travel plans and adventure goals do they make together?",
        "How do they handle meeting each other's ex-partners or past connections?",
        "What health and wellness goals do they support in each other?",
        "How do they communicate about commitment and exclusivity?",
        "What cultural differences and backgrounds do they learn about?",
        "How do they handle different communication frequencies and response times?",
        "What personal growth and self-improvement do they encourage?",
        "How do they navigate different political or social views?",
        "What milestone celebrations and special occasions do they plan?",
        "How do they handle stress and support each other during tough times?",
        "What educational or learning experiences do they share?",
        "How do they discuss children and family planning for the future?",
        "What creative projects or shared goals do they work on together?",
        "How do they handle different energy levels and social preferences?",
        "What personal space and alone time needs do they respect?",
        "How do they navigate different friendship groups and social circles?",
        "What seasonal activities and holiday traditions do they create?",
        "How do they evaluate the growth and development of their relationship?"
    ]
)
