from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Friendship Analysis Queries",
    description="Queries for analyzing friendship communication patterns.",
    questions=[
        "What shared interests and hobbies do the friends discuss most often?",
        "How do they support each other during difficult times?",
        "What inside jokes or funny memories do they reference?",
        "How do they make plans for hanging out or social activities?",
        "What personal problems or challenges do they confide in each other?",
        "How do they celebrate each other's successes and achievements?",
        "What advice do they give each other about relationships?",
        "How do they handle disagreements or conflicts between them?",
        "What travel plans or adventures do they discuss together?",
        "How do they show appreciation and gratitude for the friendship?",
        "What career or educational goals do they discuss and support?",
        "How do they share news about their daily lives and experiences?",
        "What mutual friends or social circles do they talk about?",
        "How do they comfort each other during breakups or disappointments?",
        "What movies, books, or entertainment do they recommend to each other?",
        "How do they maintain their friendship despite busy schedules?",
        "What childhood memories or past experiences do they reminisce about?",
        "How do they introduce each other to new people or experiences?",
        "What goals or dreams do they encourage each other to pursue?",
        "How do they handle jealousy or competition in their friendship?",
        "What family situations or issues do they discuss with each other?",
        "How do they show loyalty and defend each other?",
        "What health or wellness topics do they share and discuss?",
        "How do they navigate changes in their friendship over time?",
        "What creative projects or collaborations do they work on together?",
        "How do they handle gossip or drama involving mutual friends?",
        "What financial advice or money-related topics do they discuss?",
        "How do they maintain trust and confidentiality in conversations?",
        "What seasonal activities or traditions do they enjoy together?",
        "How do they balance honesty with being supportive?",
        "What life transitions or major changes do they help each other through?",
        "How do they express concern when worried about each other?",
        "What professional networking or career opportunities do they share?",
        "How do they handle different opinions on controversial topics?",
        "What spontaneous adventures or last-minute plans do they make?",
        "How do they maintain their individual identities within the friendship?",
        "What lessons or wisdom do they share from their experiences?",
        "How do they show up for each other during family emergencies?",
        "What bucket list items or life goals do they discuss achieving?",
        "How has their communication style evolved throughout their friendship?"
    ]
)
