from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Mentor-Mentee Relationship Analysis Queries",
    description="Queries for analyzing mentor-mentee relationships.",
    questions=[
        "What career goals and professional aspirations does the mentee discuss?",
        "How does the mentor share their experience and industry knowledge?",
        "What specific skills or competencies do they work on developing together?",
        "How does the mentee seek advice on challenging work situations?",
        "What networking opportunities and professional connections does the mentor provide?",
        "How do they set and track progress toward professional development goals?",
        "What feedback does the mentor give about the mentee's performance?",
        "How does the mentee express gratitude for the mentor's guidance?",
        "What industry trends and market insights do they discuss together?",
        "How does the mentor help the mentee navigate workplace politics?",
        "What educational opportunities and learning resources do they share?",
        "How do they discuss work-life balance and personal well-being?",
        "What leadership skills and management techniques does the mentor teach?",
        "How does the mentee share their challenges and obstacles with the mentor?",
        "What success stories and achievements do they celebrate together?",
        "How does the mentor provide emotional support during difficult periods?",
        "What professional certifications or qualifications do they plan for?",
        "How do they discuss salary negotiations and career advancement?",
        "What innovative ideas and creative solutions does the mentee propose?",
        "How does the mentor share lessons learned from their own mistakes?",
        "What public speaking and presentation skills do they work on?",
        "How do they navigate generational differences in workplace approaches?",
        "What ethical dilemmas and professional integrity issues do they explore?",
        "How does the mentee demonstrate initiative and proactive learning?",
        "What industry conferences and professional events do they attend together?",
        "How does the mentor help the mentee build confidence and self-advocacy?",
        "What technical skills and digital literacy do they develop?",
        "How do they discuss diversity, inclusion, and workplace equity?",
        "What entrepreneurial ideas and business ventures does the mentee explore?",
        "How does the mentor provide constructive criticism and tough feedback?",
        "What personal branding and professional reputation do they build?",
        "How do they handle setbacks and professional disappointments?",
        "What cross-functional collaboration and teamwork skills do they practice?",
        "How does the mentee contribute value back to the mentor relationship?",
        "What long-term career vision and strategic planning do they develop?",
        "How do they maintain professional boundaries while building trust?",
        "What communication and interpersonal skills do they refine together?",
        "How does the mentor prepare the mentee for leadership roles?",
        "What global perspectives and cultural competency do they explore?",
        "How do they evaluate the effectiveness and evolution of their mentoring relationship?"
    ]
)
