from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Online Community Analysis Queries",
    description="Queries for analyzing online community communication patterns.",
    questions=[
        "What topics and themes generate the most engagement and discussion?",
        "How do community members welcome and onboard new participants?",
        "What knowledge sharing and educational content do members contribute?",
        "How do they handle disagreements and maintain respectful discourse?",
        "What community guidelines and behavioral norms do they establish?",
        "How do moderators intervene and guide community interactions?",
        "What success stories and achievements do members celebrate together?",
        "How do they share resources, tools, and helpful information?",
        "What questions and help requests receive the most community support?",
        "How do members build relationships and form connections?",
        "What seasonal events and community activities do they organize?",
        "How do they handle spam, trolling, and disruptive behavior?",
        "What expertise and specialized knowledge do different members contribute?",
        "How do they encourage participation from less active members?",
        "What feedback and suggestions do members provide for community improvement?",
        "How do they coordinate offline meetups and real-world events?",
        "What collaborative projects and group initiatives do they undertake?",
        "How do they handle sensitive topics and controversial discussions?",
        "What mentorship and peer support networks naturally develop?",
        "How do they recognize and appreciate valuable community contributors?",
        "What trends and patterns emerge in community conversation topics?",
        "How do they maintain community culture during periods of growth?",
        "What cross-pollination occurs with other related communities?",
        "How do they handle member departures and community turnover?",
        "What innovative ideas and creative solutions emerge from group discussions?",
        "How do they balance casual conversation with focused topic discussion?",
        "What role do community leaders and influencers play in discussions?",
        "How do they adapt to platform changes and technical challenges?",
        "What generational or demographic differences influence communication styles?",
        "How do they maintain engagement during slow periods or low activity?",
        "What shared values and common goals unite the community members?",
        "How do they handle privacy concerns and personal information sharing?",
        "What recurring themes and inside jokes develop within the community?",
        "How do they provide emotional support during difficult times for members?",
        "What learning opportunities and skill development emerge organically?",
        "How do they handle commercial promotion and self-promotion attempts?",
        "What global perspectives and cultural diversity enrich discussions?",
        "How do they measure community health and engagement metrics?",
        "What evolution and growth patterns characterize the community over time?",
        "How do they maintain authentic connections in a digital environment?"
    ]
)
