from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Parent-Child Relationship Analysis Queries",
    description="Queries for analyzing parent-child relationship communication patterns.",
    questions=[
        "What activities did the parent and child discuss doing together?",
        "How does the parent show support for the child's interests and hobbies?",
        "What educational topics or homework help was discussed?",
        "How does the child express their feelings and emotions to the parent?",
        "What boundaries or rules were established in their conversations?",
        "How does the parent handle the child's questions about difficult topics?",
        "What praise or encouragement did the parent give to the child?",
        "How does the child ask for help or support from the parent?",
        "What conflicts or disagreements arose and how were they resolved?",
        "How does the parent teach life skills or values through conversation?",
        "What shared memories or experiences do they reference?",
        "How does the child share their daily experiences with the parent?",
        "What concerns or worries does the child express to the parent?",
        "How does the parent guide the child through challenges?",
        "What traditions or family activities do they plan together?",
        "How does the parent respond to the child's achievements?",
        "What questions does the child ask about the parent's childhood?",
        "How do they express love and affection toward each other?",
        "What future plans or goals do they discuss together?",
        "How does the parent help the child develop independence?",
        "What jokes or humor do they share in their conversations?",
        "How does the child seek the parent's opinion on decisions?",
        "What fears or anxieties does the child discuss with the parent?",
        "How does the parent prepare the child for new experiences?",
        "What creative projects or activities do they collaborate on?",
        "How does the parent handle the child's mistakes or failures?",
        "What cultural or family values are transmitted through conversation?",
        "How does the child express gratitude to the parent?",
        "What peer relationships does the child discuss with the parent?",
        "How does the parent encourage the child's self-expression?",
        "What safety topics or concerns are addressed in their talks?",
        "How does the child negotiate for privileges or permissions?",
        "What seasonal activities or holidays do they plan together?",
        "How does the parent respond to the child's changing interests?",
        "What role models or inspirational figures do they discuss?",
        "How does the child seek comfort from the parent during stress?",
        "What technology or media usage do they negotiate?",
        "How does the parent explain complex world events to the child?",
        "What personal growth milestones do they celebrate together?",
        "How do they handle disagreements about friends or social activities?"
    ]
)
