from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Sibling Analysis Queries",
    description="Queries for analyzing relationships between family members.",
    questions=[
        "What childhood memories and shared experiences do the siblings reminisce about?",
        "How do they support each other through family conflicts or issues?",
        "What inside jokes and humor do they share in their conversations?",
        "How do they coordinate care or support for aging parents?",
        "What holiday traditions and family gatherings do they plan together?",
        "How do they handle rivalry or competition between each other?",
        "What advice do they give each other about relationships and dating?",
        "How do they share news about their children and parenting experiences?",
        "What career updates and professional achievements do they celebrate?",
        "How do they maintain their relationship despite living in different places?",
        "What family secrets or sensitive topics do they discuss privately?",
        "How do they handle disagreements about family decisions?",
        "What shared hobbies or interests do they enjoy together as adults?",
        "How do they support each other during health issues or medical concerns?",
        "What financial matters or family inheritance do they coordinate?",
        "How do they comfort each other during times of loss or grief?",
        "What personality differences do they acknowledge and navigate?",
        "How do they share responsibilities for family events and celebrations?",
        "What life lessons and wisdom do they pass between each other?",
        "How do they handle favoritism or perceived unfair treatment from parents?",
        "What spouse or partner relationships do they discuss and evaluate?",
        "How do they maintain individual identities while staying connected?",
        "What travel plans or family vacations do they coordinate together?",
        "How do they handle different religious or political beliefs?",
        "What mutual friends or social connections do they share?",
        "How do they support each other's personal growth and life changes?",
        "What embarrassing or funny stories do they tease each other about?",
        "How do they coordinate gift-giving for parents and family members?",
        "What concerns about family members' well-being do they share?",
        "How do they handle being compared to each other by family or others?",
        "What educational or learning experiences do they share with each other?",
        "How do they navigate different parenting styles and approaches?",
        "What creative projects or collaborative efforts do they work on?",
        "How do they maintain loyalty while being honest about each other's flaws?",
        "What future plans for the family legacy or traditions do they discuss?",
        "How do they handle interfering or demanding extended family members?",
        "What professional networking or career opportunities do they share?",
        "How do they balance independence with family obligations?",
        "What generational differences do they bridge in family dynamics?",
        "How has their relationship evolved from childhood to adulthood?"
    ]
)
