from telegram_analyzer.questions_set import QuestionsSet

questions_set = QuestionsSet(
    title="Team Collaboration Analysis Queries",
    description="Queries for analyzing team collaboration and project management.",
    questions=[
        "How does the team coordinate project timelines and deliverable deadlines?",
        "What problem-solving approaches and solutions do team members propose?",
        "How do they distribute tasks and assign responsibilities among members?",
        "What feedback and constructive criticism do they provide to each other?",
        "How do they handle conflicts and disagreements during collaboration?",
        "What brainstorming sessions and creative ideation do they conduct?",
        "How do they communicate progress updates and status reports?",
        "What knowledge sharing and skill development occurs within the team?",
        "How do they coordinate meeting schedules and team availability?",
        "What challenges and obstacles do they identify and address together?",
        "How do they celebrate team achievements and project milestones?",
        "What resource allocation and budget discussions do they have?",
        "How do they handle different work styles and productivity preferences?",
        "What quality assurance and review processes do they establish?",
        "How do they communicate with external stakeholders and clients?",
        "What contingency planning and risk management do they discuss?",
        "How do they coordinate remote work and virtual collaboration?",
        "What training needs and professional development do they identify?",
        "How do they handle varying expertise levels and skill gaps?",
        "What documentation and knowledge management practices do they follow?",
        "How do they prioritize competing demands and urgent requests?",
        "What innovation and process improvement ideas do they generate?",
        "How do they maintain team morale and positive working relationships?",
        "What cross-functional collaboration with other teams do they coordinate?",
        "How do they handle scope changes and project modifications?",
        "What lessons learned and best practices do they share?",
        "How do they communicate technical concepts to non-technical stakeholders?",
        "What decision-making processes and authority do they establish?",
        "How do they handle team member absences and coverage needs?",
        "What performance metrics and success indicators do they track?",
        "How do they manage information overload and communication efficiency?",
        "What cultural diversity and inclusion considerations do they address?",
        "How do they handle tight deadlines and high-pressure situations?",
        "What peer mentoring and knowledge transfer occurs naturally?",
        "How do they coordinate with leadership and management expectations?",
        "What technology tools and platforms do they use for collaboration?",
        "How do they maintain work-life balance during intensive projects?",
        "What team building and relationship strengthening activities do they engage in?",
        "How do they handle constructive disagreement and healthy debate?",
        "What evolution and growth patterns emerge in their collaboration over time?"
    ]
)
